spark_locals_without_parens = [
  actor: 1,
  bindings: 1,
  channel: 2,
  channel: 3,
  contact_email: 1,
  contact_name: 1,
  contact_url: 1,
  content_type: 1,
  correlation_id: 1,
  default: 1,
  default_content_type: 1,
  default_delimiter: 1,
  default_server: 1,
  delimiter: 1,
  derive_payload_schema?: 1,
  description: 1,
  enum: 1,
  event_name: 1,
  examples: 1,
  except_fields: 1,
  external_docs: 1,
  filter: 1,
  headers: 1,
  hide_fields: 1,
  id: 1,
  include_nil_values?: 1,
  license_name: 1,
  license_url: 1,
  location: 1,
  message_name: 1,
  message_title: 1,
  name: 1,
  parameter: 1,
  parameter: 2,
  pathname: 1,
  payload_fields: 1,
  protocol: 1,
  protocol_version: 1,
  publish: 2,
  publish: 3,
  publish: 4,
  publish_all: 2,
  publish_all: 3,
  publish_all: 4,
  publish_on_notification?: 1,
  reply_channel: 1,
  security: 1,
  security_schemes: 1,
  segment_naming: 1,
  server: 2,
  server: 3,
  servers: 1,
  show_fields: 1,
  source: 1,
  subscribe: 2,
  subscribe: 3,
  subscribe: 4,
  summary: 1,
  tags: 1,
  tenant: 1,
  terms_of_service: 1,
  title: 1,
  trace?: 1,
  transform: 1,
  transport: 1,
  transport_opts: 1,
  type: 1,
  upsert?: 1,
  variables: 1,
  version: 1
]

[
  import_deps: [:ash, :spark],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 98,
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parens: spark_locals_without_parens
  ]
]
